rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
services:
  - riak
bundler_args: --without=guard
before_script:
  - ! 'echo "root: .riaktest" > spec/support/test_server.yml'
  - ! 'echo "source: /usr/sbin" >> spec/support/test_server.yml'
  - "ulimit -n 2048"
